### ISSUE TITLE
The vertical chronology is not consistent

### ISSUE THREAD

**Issue by daattali** [jumpingrivers/meetingsR#173]
That title isn't very clear, I know :)

When scrolling a page from top to bottom, you're scrolling through the years from latest to oldest. But within each year, it goes January to December. This ends up being counter intuitive to find the date you're looking for because initially you're going forward in time by scrolling down and then all of a sudden you jump a year back in time

**Comment by csgillespie** [comment]
I know - it seemed like a good idea at the time. On my list of things to change ;)

**Comment by engineerchange** [comment]
PR should resolve this; I think reverse chronology within a month might go a step too far, but reverse chronology at the month and year levels makes a ton of sense.

**Comment by engineerchange** [comment]
@csgillespie does the project have to be rebuilt for the web version to reflect the changes? I notice the web version still reflects the old changes.

**Comment by csgillespie** [comment]
travis takes care of the build (takes between 5 and 15 minutes)

Sees to be fine now https://jumpingrivers.github.io/meetingsR/events.html
