### ISSUE TITLE
Fixing some  wrong entries

### ISSUE THREAD

**Issue by mexindian** [jumpingrivers/meetingsR#27]
Hi! I'm back. I went through the Latin American links and found several wrong entries... Here are the correct groups and their links... but perhaps it would be better to  write a web-scraper to check all the links to at least identify all the mistakes? I think if you're going to maintain this list, it should be up to date, otherwise we're all just copypasting the list from that original Revolutions thing :D

Buenos Aires<a href="http://ar.i314.com.ar/"> Grupo de Usarios de R Argentina</a><br>
Brasilia<a href="http://www.meetup.com/Brasilia-UseR-Meetup/">Brasilia User Group</a><br>
Campinas<a href="http://www.meetup.com/Campinas-R-Users-Meetup/"> Campinas R Users Meetup</a><br>
Porto Alegre<a href="http://www.meetup.com/RStat-RS-R-User-Group/"> RStat</a><br>
São Paulo<a href="http://www.meetup.com/useR-SP/"> São Paulo R Users Group</a><br>
Virtual<a href="http://leg.est.ufpr.br/doku.php/software:rbr"> R-br</a><br>
Santiago<a href="http://www.meetup.com/useRchile/"> Grupo de Usuarios de R en Chile</a><br>
Bogota<a href="http://www.meetup.com/it/Bogota-R-Users-Group/"> Bogotá R Users Group</a><br>
Cali<a href="http://www.meetup.com/R-Users-Group-Cali/"> Cali R Users Group</a><br>
Quesada<a href="http://www.meetup.com/San-Carlos-R-User-Group/"> San Carlos R Users Group</a><br>
Santo Domingo<a href="http://www.meetup.com/Santo-Domingo-R-useR-Group/"> Santo Domingo R user Group</a><br>
Quito<a href="http://www.meetup.com/Usuarios-de-R-Ecuador/"> Usuarios de R Ecuador</a><br>
Guadalajara<a href="https://www.meetup.com/Guadalajara-R-Users-Group-Meetup/"> Guadalajara R Users group Meetup</a><br>
Mexico City<a href="http://www.meetup.com/Mexico-City-Business-Analytics-Users/events/219135766/"> Mexico City Business Analytics Users Group</a><br>
Mexico City<a href="http://www.meetup.com/The-Mexico-City-R-Users-Group/"> The Mexico City R Users Group</a><br>
Tecate<a href="https://www.meetup.com/Tecate-BC-Mexico-R-Users-Group-Meetup/"> ecate BC Mexico R Users Group Meetup</a><br>
Managua<a href="https://www.facebook.com/groups/usuariosrnicaragua/"> Usuarios R Nicaragua</a><br>
Caracas<a href="http://www.meetup.com/R-usersVEN"> R-usersVEN</a><br>

**Comment by csgillespie** [comment]
Thanks. My plan is eventually to parse the Rmd and, inter alia, check links.
