### ISSUE TITLE
UK and United Kingdom present in groups.csv file

### ISSUE THREAD

**Issue by benubah** [jumpingrivers/meetingsR#91]
We find 'UK' and 'United Kingdom' present in groups.csv file here: https://github.com/jumpingrivers/meetingsR/blob/master/_book/groups.csv

Please consider updating and possibly replace UK with United Kingdom.

Thank you

**Comment by csgillespie** [comment]
Already fixed.

However, that link points to an old version (I'll delete that one). At https://jumpingrivers.github.io/meetingsR/the-data.html the link points to https://jumpingrivers.github.io/meetingsR/groups.csv
